name: Hotfix

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g. 123)'
        required: true
        type: number

env:
  REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}
  APP_NAME: app

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        id: checkout-branch
        uses: actions/checkout@v4
        with:
          ref: releases/${{ github.event.inputs.release_version }}
          fetch-depth: 0
        continue-on-error: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: |
          npm run lint
          npm run test

      - name: Get hotfix number
        id: hotfix
        run: echo "number=${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Login to Yandex Container Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.YC_AUTH_TOKEN }}

      - name: Build and push Docker image
        run: |
          FIX_TAG="${{ github.event.inputs.release_version }}_fix${{ steps.hotfix.outputs.number }}"

          docker build -t ${{ env.REGISTRY_ID }}/${{ env.APP_NAME }}:$FIX_TAG .
          docker tag ${{ env.REGISTRY_ID }}/${{ env.APP_NAME }}:$FIX_TAG \
                     ${{ env.REGISTRY_ID }}/${{ env.APP_NAME }}:${{ github.event.inputs.release_version }}_latest

          docker push ${{ env.REGISTRY_ID }}/${{ env.APP_NAME }}:$FIX_TAG
          docker push ${{ env.REGISTRY_ID }}/${{ env.APP_NAME }}:${{ github.event.inputs.release_version }}_latest

      - name: Create fix tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          TAG_NAME="v${{ github.event.inputs.release_version }}_fix${{ steps.hotfix.outputs.number }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Get commits since last release
        id: commits
        run: |
          RELEASE_TAG_PATTERN="v${{ github.event.inputs.release_version }}*"
          PREV_TAG=$(git tag --list "$RELEASE_TAG_PATTERN" --sort=-v:refname | head -n 1 || echo "")
          
          if [ -z "$PREV_TAG" ]; then
            echo "No previous tags found, using all commits in branch"
            COMMITS=$(git log --pretty=format:"- %s (%h)")
          else
            echo "Using previous tag: $PREV_TAG"
            COMMITS=$(git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)")
          fi
          
          # Безопасный вывод многострочных данных
          DELIMITER="EOF_$(date +%s)"
          echo "commits<<$DELIMITER" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "$DELIMITER" >> $GITHUB_OUTPUT

      - name: Find release issue
        id: find-issue
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.search.issuesAndPullRequests({
              q: `repo:${context.repo.owner}/${context.repo.repo} in:title "Release ${{ github.event.inputs.release_version }}"`
            });
            return data.items[0]?.number || 0;
          result-encoding: string

      - name: Comment on issue
        if: ${{ steps.find-issue.outputs.result != '0' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.find-issue.outputs.result }},
              body: `**Hotfix Date:** ${new Date().toISOString()}\n` +
                     `**Author:** ${context.actor}\n` +
                     `**Commits:**\n${{ steps.commits.outputs.commits }}\n` +
                     `**Docker Image:** ${{ env.REGISTRY_ID }}/${{ env.APP_NAME }}:${{ github.event.inputs.release_version }}_fix${{ steps.hotfix.outputs.number }}`
            });